import asyncio
import json
import os
import tempfile
from pathlib import Path
from typing import Any


def _size_bucket(n_pages: int) -> str:
    for limit, label in ((1_000, "n<1K"), (10_000, "1K<n<10K"),
                         (100_000, "10K<n<100K"), (1_000_000, "100K<n<1M")):
        if n_pages < limit:
            return label
    return "1M<n<10M"


def _build_dataset_card(
    run: dict[str, Any],
    documents: list[dict[str, Any]],
    pages_parquet: Path,
    documents_parquet: Path,
) -> str:
    languages: set[str] = set()
    scripts: set[str] = set()
    totals = {"pass": 0, "warn": 0, "fail": 0, "empty": 0, "pages": 0}
    for d in documents:
        for k in ("pass", "warn", "fail", "empty"):
            totals[k] += d.get(f"pages_{k}") or 0
        totals["pages"] += d.get("total_pages") or 0
        if d.get("dominant_script"):
            scripts.add(d["dominant_script"])
        languages.update(str(x) for x in (json.loads(d.get("languages_detected") or "[]") or []))

    yaml_lang_block = "\n".join(f"  - {lang}" for lang in (sorted(languages) or ["en"]))

    front_matter = (
        "---\n"
        "license: cc-by-4.0\n"
        "task_categories:\n  - text-generation\n  - feature-extraction\n"
        f"language:\n{yaml_lang_block}\n"
        "tags:\n  - ocr\n  - opencr\n  - cdli-ai\n  - deepseek-ocr\n  - pdf\n"
        f"size_categories:\n  - {_size_bucket(totals['pages'])}\n"
        "---\n"
    )

    body = "\n".join([
        f"# OpenCR Dataset — Run `{run['id']}`",
        "",
        f"Generated by **[OpenCR](https://cdli.ai)** (cdli.ai) using "
        f"`{run.get('model_used', 'DeepSeek-OCR')}` on "
        f"{run.get('completed_at') or run.get('created_at')}.",
        "",
        "## Summary",
        "",
        f"- **Documents:** {len(documents)}",
        f"- **Pages:** {totals['pages']}",
        f"- **Quality:** {totals['pass']} pass · {totals['warn']} warn · "
        f"{totals['fail']} fail · {totals['empty']} empty",
        f"- **Scripts:** {', '.join(sorted(scripts)) or 'unknown'}",
        f"- **Pipeline version:** {run.get('pipeline_version', 'n/a')}",
        "",
        "## Files",
        "",
        f"- `{pages_parquet.name}` — one row per OCRed page",
        f"- `{documents_parquet.name}` — one row per document (joined text + summaries)",
        "- `manifest.json` — schema, split strategy, source documents",
        "",
        "## Splits",
        "",
        "Deterministic by SHA256 bucket on document id (90% train / 5% validation / "
        "5% test). Use the `split` column.",
        "",
        "## Loading",
        "",
        "```python",
        "from datasets import load_dataset",
        f'ds = load_dataset("{run.get("hf_repo_id", "<repo_id>")}", '
        'data_files={"pages": "pages.parquet", "documents": "documents.parquet"})',
        "```",
        "",
        "---",
        "",
        "Made by **[cdli.ai](https://cdli.ai)** · OpenCR is open source.",
        "",
    ])
    return front_matter + body


def _resolve_token(token: str | None) -> str | None:
    return token or os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")


async def publish_run_to_hf(
    *,
    run: dict[str, Any],
    documents: list[dict[str, Any]],
    dataset_dir: Path,
    repo_id: str,
    private: bool = False,
    token: str | None = None,
    commit_message: str | None = None,
) -> dict[str, Any]:
    pages_parquet = dataset_dir / "pages.parquet"
    documents_parquet = dataset_dir / "documents.parquet"
    manifest = dataset_dir / "manifest.json"

    if not pages_parquet.exists() or not documents_parquet.exists():
        raise FileNotFoundError(
            "Dataset Parquet files not found. Run with export_parquet=true first."
        )

    resolved_token = _resolve_token(token)
    if not resolved_token:
        raise RuntimeError("No HuggingFace token available. Pass `token` or set HF_TOKEN.")

    from huggingface_hub import HfApi
    api = HfApi(token=resolved_token)

    def _do_publish() -> dict[str, Any]:
        api.create_repo(repo_id=repo_id, repo_type="dataset", private=private, exist_ok=True)
        with tempfile.TemporaryDirectory() as tmp_str:
            tmp = Path(tmp_str)
            (tmp / "pages.parquet").write_bytes(pages_parquet.read_bytes())
            (tmp / "documents.parquet").write_bytes(documents_parquet.read_bytes())
            if manifest.exists():
                (tmp / "manifest.json").write_bytes(manifest.read_bytes())
            (tmp / "README.md").write_text(
                _build_dataset_card({**run, "hf_repo_id": repo_id},
                                    documents, pages_parquet, documents_parquet),
                encoding="utf-8",
            )
            commit_info = api.upload_folder(
                repo_id=repo_id,
                repo_type="dataset",
                folder_path=str(tmp),
                commit_message=commit_message or f"Publish OpenCR run {run['id']} (cdli.ai)",
            )
        return {
            "repo_id": repo_id,
            "repo_url": f"https://huggingface.co/datasets/{repo_id}",
            "commit_url": getattr(commit_info, "commit_url", None),
            "files_uploaded": ["pages.parquet", "documents.parquet", "manifest.json", "README.md"],
        }

    return await asyncio.to_thread(_do_publish)
